### ISSUE TITLE
Support github emojis when display the profile

### ISSUE THREAD

**Issue by Almo7aya** [aman-roy/StalkHub#13]
Hello,
I like the idea of this project, but I found an issue when display the profile,

the emojis don't appear 
![issue1-1](https://user-images.githubusercontent.com/17254073/39441397-71ea8e96-4cb6-11e8-941b-402863d3f5aa.PNG)
as the github shows them
![issue1-2](https://user-images.githubusercontent.com/17254073/39441421-8a0ecfa0-4cb6-11e8-9aa1-c655d2518ddb.PNG)

you may use this
https://github.com/zzarcon/gh-emoji

**Comment by aman-roy** [comment]
I will look into that. If you want to resolve this. Send me PR for sure. :smile:
