### ISSUE TITLE
some icon images are not visible

### ISSUE THREAD

**Issue by lalitsom** [aman-roy/StalkHub#4]
![asd](https://user-images.githubusercontent.com/23455413/29812190-6db939e8-8cc3-11e7-86ee-c0384ba3f487.JPG)

Hi,
 your "face" icon image and "eject" image and many more are not visible on "https" , check the image I have added with console errors. You are using some files over http from different servers maybe that's why.
I have to click on load unsafe scripts to load them manually.
May be you can download those files, and then use them from your root directory, 
or you can change http to https, I have created a pull request for the same.

**Comment by aman-roy** [comment]
Merged your pull request. Thank you.
