### ISSUE TITLE
Add a contribution graph to the profile page.

### ISSUE THREAD

**Issue by aman-roy** [aman-roy/StalkHub#6]
Something like this:
![screenshot from 2017-10-09 06-43-14](https://user-images.githubusercontent.com/13317901/31322907-2d1b691e-acbd-11e7-846c-15438d53e8ed.png)
-

**Comment by Priyansh2** [comment]
@aman-roy do you want this to be an additional feature to your project . I mean it should also show this github calender when any user entered his/her username in your application , am i right ? If this is the issue then you can try this  https://stackoverflow.com/questions/34516592/embed-github-contributions-graph-in-website

**Comment by aman-roy** [comment]
@Priyansh2 If you want to do this, you can. I want it to be done by someone under hacktoberfest.

**Comment by Priyansh2** [comment]
@aman-roy ok i will try
