### ISSUE TITLE
Making profile page dynamic.

### ISSUE THREAD

**Issue by aman-roy** [aman-roy/StalkHub#8]
The profile page of the app is not fitted to screen in a mobile device. It's working good on big screens but fails to render dynamically on small screens due to contribution chart element.

**Comment by shalithasuranga** [comment]
Hi.. I like to work with this

**Comment by aman-roy** [comment]
Thanks, Go for it.

**Comment by shalithasuranga** [comment]
@aman-roy  I am added `overflow-x:scroll ` when width is less than calendar width + some offset 

Comparison
https://github.com/aman-roy/StalkHub/compare/master...shalithasuranga:layout

Note 
I need to test before making PR

**Comment by aman-roy** [comment]
Ok test it well before making a PR

**Comment by shalithasuranga** [comment]
@aman-roy  please review the PR #11
